### ISSUE TITLE
Long initialisers problem.

### ISSUE THREAD

**Issue by radekcieciwa** [badoo/ios-guidelines#9]
# Rationale

We identify that some of our initialisers (and/or functions) have too many params. This may be a **code smell** that we should identify and fix in appropriate places (where applicable). 

Why it's identified as a problem/code smell?
This may indicate that the entity/class have too many dependencies. Thus possibly it may violate SRP (Simple Responsibility Principle ^1) or any other well named OOD good practice.

### Initialisers with 10 or more params per app

| Badoo    | 58 |
| Bumble   |  8 |
| Platform | 16 |

### Initialisers with 15 or more params per app

| Badoo    | 17 |
| Bumble   |  3 |
| Platform |  4 |

# Problem shade no. 2
Some of the arguments in initializers are _transitive_, meaning that they are passed to object not to interact directly, but to be passed later to created object, or to super initializer. 

**pass arguments to super (vertically transitive dependencies ^2)**
I personally don't know how to asses this problem differently than redesigning the object (aka, refactor). 
Examples likes: `ChatViewController`

**pass argument to create later (postponed transitive dependencies ^2)**
For the passed object to be created later, builder/factory pattern should be enough. 

# "typealias Services" pattern

One of many solutions is a pattern we use in Bumble app (Badoo apply this as well - always?). We use 

`typealias Services = <Providers>`

`<Service>Provider` returns specific Service in example:

```
protocol NetworkServiceProvider {
  var networkService: NetworkServiceProtocol { get }
}
extension BPFGlobals: NetworkServiceProvider { 
  var networkService: NetworkServiceProtocol { /* done by service locator */ } 
}
```

This is quite nice and readable pattern to aggregate Services that are kept in BPFGlobals, or generally can be provided via <Service>Provider pattern in one DI Container per object that is defined in file as well. This allows for future optimisations when you need to create subject with it's own services requirements.

`typealias Services = SubType.Services & SecondSubType.Services`

# Extraction building of object to higher level

Don't go into details, but here instead of passing dependencies of class you want to instantiate inside of your type, you would take builder of this type instead to move this dependency to higher level.

# Know popular patterns

* Extract method
* DataClumps
* Parameter Object

==
^1 Yes, I know it's "Single" :)
^2 I'm inventing those names

**Comment by radekcieciwa** [comment]
For this particular Issue I wanted to formalised `typealias Services = <Providers>` only. But the topic should be discussed holistically 🤓.

**Comment by wiruzx** [comment]
@radekcieciwa I've seen many times when "Services Pattern" hides transitive dependencies in our code. What many people do is
``` swift
typealias Services = Dependency.Services & AnotherDependency.Services
```
And then create dependencies inside of the class itself. 
Just saying that it doesn't solve all the issues and we should be careful with that

**Comment by radekcieciwa** [comment]
@wiruzx I agree, problematic part about it, is the having (or not) the pattern itself doesn't protect us from it. In other case someone would just declare them directly, like so:

```
typealias Services = 
    DepedencyFirstOneProvider & 
    DepedencySecondOneProvider & 
    AnotherDependency.Services(...)
```

Instead of 
```
typealias Services = Dependency.Services & AnotherDependency.Services
```

As the problem is how we instantiate sub entities - all in all, you would need to have those dependencies inside to use them to create those sub entities (either via compound or separately services, either via BPFGlobals directly.
